# Generated by Django 4.1.2 on 2022-10-05 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'тренера', 'verbose_name_plural': 'тренера'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='device_id',
            field=models.CharField(max_length=150, verbose_name='устройство №'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='юзернейм'),
        ),
    ]
